theme: jekyll-theme-minimal
logo: Github_1.jpeg
github:
  is_project_page: false

description: - Postdoctoral Research Associate, Department of Biosciences, University of Sheffield (2021 - present)
- PhD Yusef Hamied Department of Chemistry, University of Cambridge (2018-2021)
- MA, MSci Natural Sciences (Chemistry) Pembroke College, University of Cambridge (2012-2016)
