theme: jekyll-theme-minimal
logo: Github_1.jpeg
github:
   is_project_page: false
description: Email j.weber@sheffield.ac.uk

color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
favicon: true

